services:
  frontend:
    build: ./frontend
    container_name: edgesurvivor_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: edgesurvivor_backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: mariadb:10.11
    container_name: edgesurvivor_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edgesurvivor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
