services:
  frontend:
    build: ./frontend
    container_name: edgesurvivor_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: edgesurvivor_backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=edgesurvivor
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: edgesurvivor_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edgesurvivor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
