# 簡化版 Docker Compose - 用於測試
version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: edgesurvivor_db_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edgesurvivor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - test_db_data:/var/lib/mysql

volumes:
  test_db_data:
